[workspace]
members = [
    "wundergraph",
    "wundergraph_derive",
    "wundergraph_example",
    "wundergraph_cli",
]

[replace]
"diesel:1.2.2" = { git = "https://github.com/weiznich/diesel", rev = "deb2cd532d05" }
"diesel_migrations:1.2.0" = { git = "https://github.com/weiznich/diesel", rev = "deb2cd532d05" }
"migrations_internals:1.2.0" = { git = "https://github.com/weiznich/diesel", rev = "deb2cd532d05" }
"migrations_macros:1.2.0" = { git = "https://github.com/weiznich/diesel", rev = "deb2cd532d05" }
"diesel_derives:1.2.0" = { git = "https://github.com/weiznich/diesel", rev = "deb2cd532d05" }
"juniper:0.9.2" = { git = "https://github.com/graphql-rust/juniper/", rev = "7933bf9" }
"juniper_codegen:0.9.2" = { git = "https://github.com/graphql-rust/juniper/", rev = "7933bf9" }
"juniper_rocket:0.1.2" = { git = "https://github.com/graphql-rust/juniper/", rev = "7933bf9" }
